version: '3'

services:
  containerdasample:
    image: containerdasample
    build:
      context: ./Src/ContainerDASample
      dockerfile: Dockerfile
#    ports:
#      - 5000:5000
    network_mode: host
      
