version: '3'

services:
  dockerpostgres:
    image: postgres-server
    restart: always
    build:
      context: ./dbscripts
      dockerfile: Dockerfile
    ports:
      - 5601:5432
    environment:
      POSTGRES_DB: ASPNETCORE
      POSTGRES_PASSWORD: venkat78
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
    - containernetwork
  containerda:
    image: containerda-img
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:80
    links:
      - dockerpostgres
    depends_on:
      - "dockerpostgres"
    networks:
      - containernetwork
volumes:
  pgdata:
networks:
  containernetwork:
    driver: bridge